=== Nictiz/Geboortezorg/Publicaties/20180320/peri/2_3/kernset_geboortezorg/wrapper/input_wrapper.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="transmission_wrapper">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="schematron_href" minOccurs="0"/>
        <xs:element ref="schema_location" minOccurs="0"/>
        <xs:element ref="root_xml_element" minOccurs="0"/>
        <xs:element ref="id" minOccurs="0"/>
        <xs:element ref="creation_time" minOccurs="0"/>
        <xs:element ref="interaction_id" minOccurs="0"/>
        <xs:element ref="accept_ack_code" minOccurs="0"/>
        <xs:element ref="receiver" minOccurs="0"/>
        <xs:element ref="sender" minOccurs="0"/>
        <xs:element ref="controlact_wrapper" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="schematron_href">
    <xs:complexType>
      <xs:attribute name="value" use="optional" type="xs:anyURI"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="schema_location">
    <xs:complexType>
      <xs:attribute name="value" use="optional"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="root_xml_element">
    <xs:complexType>
      <xs:attribute name="value" use="optional" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="creation_time">
    <xs:complexType>
      <xs:attribute name="value" use="optional" type="xs:dateTime"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="interaction_id">
    <xs:complexType>
      <xs:attribute name="value" use="optional" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="accept_ack_code">
    <xs:complexType>
      <xs:attribute name="value" use="optional" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="receiver">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="id" minOccurs="0"/>
        <xs:element ref="name" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="sender">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="id"/>
        <xs:element ref="name"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="controlact_wrapper">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="author_or_performer" minOccurs="0"/>
        <xs:element ref="overseer" minOccurs="0"/>
        <xs:element ref="registration_wrapper" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="author_or_performer" type="assigned_person"/>
  <xs:element name="overseer" type="assigned_person"/>
  <xs:element name="registration_wrapper">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="code" minOccurs="0"/>
        <xs:element ref="effective_time" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="effective_time">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="low" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="low">
    <xs:complexType>
      <xs:attribute name="value" use="optional" type="xs:dateTime"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="id">
    <xs:complexType>
      <xs:attribute name="root" use="optional" type="xs:NMTOKEN"/>
      <xs:attribute name="value" use="optional" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="name">
    <xs:complexType>
      <xs:attribute name="value" use="optional"/>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="assigned_person">
    <xs:sequence>
      <xs:element ref="assigned_person" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="assigned_person">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="id"/>
        <xs:element ref="code" minOccurs="0"/>
        <xs:element ref="name" minOccurs="0"/>
        <xs:element ref="organization" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="organization">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="id"/>
        <xs:element ref="code" minOccurs="0"/>
        <xs:element ref="name" minOccurs="0"/>
        <xs:element ref="address" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="address">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="city" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="city">
    <xs:complexType>
      <xs:attribute name="value" use="optional" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="code">
    <xs:complexType>
      <xs:attribute name="code" use="optional" type="xs:NMTOKEN"/>
      <xs:attribute name="codeSystem" use="optional" type="xs:NMTOKEN"/>
      <xs:attribute name="displayName" use="optional"/>
      <xs:attribute name="value" use="optional" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Nictiz/Geboortezorg/Publicaties/20180320/ada_2_hl7/peri/2_3/kernset_geboortezorg/wrapper/input_wrapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<transmission_wrapper xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="input_wrapper.xsd">
    <schematron_href value="file:/C:/SVN/AORTA/trunk/Zorgtoepassing/PerinataleZorg/DECOR/peri20-runtime-develop/peri20-ksgz-alg-23.sch"/>
    <schema_location value="urn:hl7-org:v3 file:/C:/SVN/AORTA/trunk/XML/schemas_codeGen/REPC_IN004014NL.xsd"/>
    <!-- vaste waarde voor Kernset -->
    <root_xml_element value="REPC_IN004014NL"/>
    <!-- assign proper OID and generate unique id -->
    <id value="generate_id" root="1.2.3.999"/>
    <!-- generate date/time of message creation -->
    <creation_time value="generate_time"/>
    <!-- vaste waarde voor Kernset -->
    <interaction_id value="REPC_IN004014NL"/>
    <!-- vaste waarde voor Kernset -->
    <accept_ack_code value="AL"/>
    <receiver>
        <!-- vaste waarden voor Perined -->
        <id value="2BFilledWithRealValue" root="1.2.3.999"/>
        <name value="Perined"/>
    </receiver>
    <sender>
        <!-- afhankelijk van zendende instelling/softwareapplicatie -->
        <id value="2BFilledWithRealValue" root="1.2.3.999"/>
        <name value="Verloskundige praktijk X"/>
    </sender>
    <controlact_wrapper>
        <author_or_performer>
            <assigned_person>
                <id value="123456789" root="2.16.528.1.1007.3.1"/>
                <id value="12345678" root="2.16.840.1.113883.2.4.6.1"/>
                <!-- Zorgverlenertype -->
                <code value="01.046" code="01.046" codeSystem="2.16.840.1.113883.2.4.15.111" displayName="Gynaecoloog"/>
                <name value="Peter van den Broek"/>
                <organization>
                    <!-- eigen OID -->
                    <id value="2BFilledWithRealValue" root="2.16.840.1.113883.2.4.3.11.21"/>
                    <!-- URA -->
                    <id value="13265478" root="2.16.528.1.1007.3.3"/>
                    <code value="V4" code="V4" codeSystem="2.16.840.1.113883.2.4.15.1060" displayName="Ziekenhuis"/>
                    <name value="Ziekenhuis X"/>
                    <address>
                        <city value="Lutjebroek"/>
                    </address>
                </organization>
            </assigned_person>
        </author_or_performer>
        <overseer>
            <assigned_person>
                <id value="123456798" root="2.16.528.1.1007.3.1"/>
                <id value="12365487" root="2.16.840.1.113883.2.4.6.1"/>
                <!-- Zorgverlenertype -->
                <code value="01.046" code="01.046" codeSystem="2.16.840.1.113883.2.4.15.111" displayName="Gynaecoloog"/>
                <name value="Peter van den Broek"/>
                <organization>
                    <!-- eigen OID -->
                    <id value="2BFilledWithRealValue" root="2.16.840.1.113883.2.4.3.11.21"/>
                    <!-- URA -->
                    <id value="12346548" root="2.16.528.1.1007.3.3"/>
                    <code value="V4" code="V4" codeSystem="2.16.840.1.113883.2.4.15.1060" displayName="Ziekenhuis"/>
                    <name value="Ziekenhuis X"/>
                    <address>
                        <city value="Lutjebroek"/>
                    </address>
                </organization>
            </assigned_person>
        </overseer>
        <registration_wrapper>
            <!-- vaste waarde voor Kernset -->
            <code value="900000" code="900000" codeSystem="2.16.840.1.113883.2.4.15.4" displayName="Perinatale Care Provision"/>
            <effective_time>
                <low value="2017-08-08T12:30:30"/>
            </effective_time>
            <!-- Hier komt de echte Payload van de Kernset -->

        </registration_wrapper>
    </controlact_wrapper>
</transmission_wrapper>
